name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking changes'
    labels: ['breaking']
  - title: 'Features'
    labels: ['enhancement']
  - title: 'Bug fixes'
    labels: ['bug']
  - title: 'Performance'
    labels: ['performance']
  - title: 'Documentation'
    labels: ['documentation']
  - title: 'Maintenance'
    labels: ['chore', 'dependencies']

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['enhancement']
  patch:
    labels: ['bug', 'performance', 'documentation', 'chore', 'dependencies']
  default: patch

autolabeler:
  - label: 'breaking'
    title: ['/^\w+(\(.+\))?!:/']
  - label: 'enhancement'
    title: ['/^feat(\(.+\))?!?:/']
  - label: 'bug'
    title: ['/^fix(\(.+\))?!?:/']
  - label: 'performance'
    title: ['/^perf(\(.+\))?!?:/']
  - label: 'documentation'
    title: ['/^docs(\(.+\))?!?:/']
  - label: 'chore'
    title: ['/^(chore|build|ci|test|refactor|style)(\(.+\))?!?:/']

template: |
  $CHANGES

  **Full changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
