[package]
name = "volare"
version = "0.2.1"
edition = "2024"
license = "Apache-2.0"
description = "Capacitated vehicle routing solver with no dependencies"
repository = "https://github.com/thiagomoretto/volare"
readme = "README.md"
keywords = ["cvrp", "vrp", "routing", "optimization", "solver"]
categories = ["algorithms", "science"]
exclude = ["instances", "baseline.csv"]

[dependencies]
